import { ItemTypes } from 'src/types/item';

const items = [
    {
        id: 0,
        name: 'wood',
        mass: 2000,
        width: 6,
        height: 2,
        maxStack: 1,
    },
    {
        id: 1,
        name: 'stick',
        mass: 10,
        width: 1,
        height: 2,
        maxStack: 10,
    },
    {
        id: 2,
        name: 'iron ore',
        mass: 1000,
        width: 1,
        height: 1,
        maxStack: 1,
    },
    {
        id: 3,
        name: 'iron bullion',
        mass: 500,
        width: 1,
        height: 1,
        maxStack: 1,
    },
    {
        id: 4,
        name: 'coal',
        mass: 1000,
        width: 2,
        height: 2,
        maxStack: 5,
    },
    {
        id: 5,
        name: 'Левый верхний подсумок на предплечие',
        type: 'STORE',
        mass: 200,
        width: 2,
        height: 1,
        innerSpace: {
            x: 1,
            y: 2,
        },
        inner: [],
    },
    {
        id: 6,
        name: 'правый верхний подсумок на предплечие',
        type: 'STORE',
        mass: 200,
        width: 2,
        height: 1,
        innerSpace: {
            x: 1,
            y: 2,
        },
        inner: [],
    },
];
